### PR TITLE
Refactor tests with esm

### PR DESCRIPTION
**Pull request by TrySound**
Tap supports esm out of the box. We may just use it even with commonjs
implementation. The syntax is nice and no need to add `use strict`
annotation to each file.

### CODE REVIEW

**Comment by fannarsh** [comment]
Thanks for showing interest.
But unfortunately I will need to close this PR without merging since I don't intend to have the tests in esm since that prevents me from running them directly in node.

**Comment by TrySound** [comment]
You may run tests directly this way `node -r esm test/get-code.js`

**Comment by fannarsh** [comment]
Doesn't `-r esm`  requires having `https://github.com/standard-things/esm` installed?

**Comment by TrySound** [comment]
It's already in node_modules hoisted from tap. Though yeah, it can be installed.

**Pull request closed without merging**
